### ISSUE TITLE
Camilladsp requirements and minimal hardware configuration.

### ISSUE THREAD

**Issue by szpsz** [HEnquist/camilladsp#100]
The project is one of the best documented DSP I found (congrats!) so it would be perfect to use in simple active crossovers. The one thing I couldn't find in the repository is the minimal hardware configuration. Is it possible to run the software on raspberry pi 2/3/4/0 and have reasonable delay?

**Comment by HEnquist** [comment]
Thanks! 
I didn't write anything about requirements since there are no strict limits. It all depends on what you want to do.
A Raspberry Pi 2, 3 or 4 works very well and can do quite significant processing, with FIR filters, resampling etc. 
I have not tried on a Pi 0 or 1, but I would expect that it would be able to do IIR crossovers just fine if compiled in 32-bit mode. 
On x86, anything made during the last 15 years or so should do just fine.

The delay mostly depends on the length of FIR filters. Of course a faster cpu can push the data through the pipeline faster, but this difference isn't very large.

**Comment by HEnquist** [comment]
I included a section on this in the readme for next version:
https://github.com/HEnquist/camilladsp/blob/develop/README.md#system-requirements
I'm closing this issue for now, but pleaso reopen if you think something important is missing.
