### ISSUE TITLE
crossfeed

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#117]
Hi, is there a way to do crossfeed simulation? The Bauer model  (ref. to the bs2b project) is just a simple IIR + delay, which should be possible to be implemented with existing camiladsp features. I think it's not hard to implement a shortcut with variable filter frequency + damping factor. similar to how the loudness shortcut presented here. Thanks.

**Comment by HEnquist** [comment]
Crossfeed is certainly possible. There is an example here: https://www.bitlab.nl/page_id=665
Direct link to the config: https://www.bitlab.nl/wp-content/uploads/2021/03/linkwitz_1971.yml

If you use the gui, then it becomes easy to change filter frequencies, gains etc. At the moment you have to apply the new config after you change a parameter. But at some point the gui will support an immediate mode where changes are applied live.

**Comment by Wang-Yue** [comment]
yeah, that's why I suggest adding a bs2b equivalent shorthand similar to the loudness shorthand in your project.
the bs2b model is the most widely used one --- RME ADI-2 DAC is also based on that.

**Comment by HEnquist** [comment]
All filters in CamillaDSP, including the loudness filter, works on each single channel independently. Since the crossfeed needs to work on two channels, implementing crossfeed like this would require very large changes that would make the processing pipeline much more complicated. I'm sorry but this isn't a big enough problem to be worth that.
