### ISSUE TITLE
camilladsp as a library

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#119]
With a few audio player projects that are using camilladsp as the dsp engine, it's time to think about ways to better integrate it into music player projects rather than a standalone program. 
As far as i see, SuperPlayer or moode all hacked the system heavily to make it work with either mpd or squeezelite. but those integrations are not perfect:

1. it requires heavy configuration of internal routing for it to work.  it's not only less efficient and has longer latency(as ipc is involved), people also lose the ability to configure audio output using their native OS output plugins. on some platforms it also requires to install additional OS level extension--- we end up with more kernel module dependencies and a less safe system. 

2. the way those projects handle sample rate changes are very hacky and fragile. 

I would suggest to start working a c api that could make the dsp engine work as a library. similar to what libavfilter has but a lot simpler. Once that is done, MPD already has plugin support for filters, and should be easy to integrate. 

Users will benefit a lot in this:

1. easy to install. camilladsp can be built with the MPD binary, and there's no need to try out a specific Linux distribution. I have yet seen hacks similar to moode on OS X or Windows albeit doable. but running as a library would eliminate the need to do those hacks.
2. works for all existing OS output, and supports various OS audio stack features. For example, wasapi has exclusive mode. CoreAudio has similar mode called "hog". it should be the player's responsiblity to customize those flags, not dsp engine. 
3. dsp process would be seamless and no user interaction/script automation is required when switching tracks
4. better performance as there's no ipc needed. only memcpy. between host and dsp engine. no hiccups. everything's performance is determined and under control. 

It is possible to do DSP (such as parametric eq, crossfeed, etc) via libavfilter in MPD already. I'm using my dsp filter graph with it nowadays. But I like camilladsp's config format better, and it seems to have more runtime flexibilities.

**Comment by HEnquist** [comment]
I didn't consider building a camilladsp-lib, might be interesting. But it requires very substantial changes since it's really not designed with this in mind.
Making a lib would give the advantages you describe. The very big disadvantage is that every player app needs to use this library to use the dsp, there will be nothing system-wide. So it's a niche use case for when using only a very short list of apps, that all implement the dsp. 
I would also think that implementing a crossover inside for example mpd is non-trivial since then the dsp suddenly outputs more channels than its input. 
Anyway, I will think a little about it. But I should mention that if I decide to go this route, it won't happen anytime soon.

**Comment by Wang-Yue** [comment]
> Making a lib would give the advantages you describe. The very big disadvantage is that every player app needs to use this library to use the dsp, there will be nothing system-wide. So it's a niche use case for when using only a very short list of apps, that all implement the dsp.


I would say this could be done gradually. first step is to split the codebase to system independent code vs depended one.  
then make the previous a library, and make the latter a program similar to what you already have to call the previous one. 
You don't lose the ability to do system wide dsp in this case.
This is similar to ffmpeg --- its filters are all reusable by other applications, while the ffmpeg program calls its filter library to do the conversion. 
I don't feel it's a niche case --- as far as I see it, music players are the biggest customers of your dsp engine. 

> I would also think that implementing a crossover inside for example mpd is non-trivial since then the dsp suddenly outputs more channels than its input.

MPD has channel mapping in its output stage so  a channel mapping from 2->4 is possible  (my MPD OS X plugin has that feature). but we want the filter stage to happen after the channel mapping. So yes, a lot of work needs to be done on the MPD side to make that happen.

MPD needs to have a DSP pipeline to better support such transformation. However I don't think the developer is interested in that.

**Comment by HEnquist** [comment]
> I would say this could be done gradually. first step is to split the codebase to system independent code vs depended one.
> then make the previous a library, and make the latter a program similar to what you already have to call the previous one.
> You don't lose the ability to do system wide dsp in this case.

The code is already organized a bit like that, but it's not completely separated. But there is another step needed. By just splitting I get a Rust library. This then needs to be wrapped up as a c library, with functions taking c types instead of the Rust data structures.
The thing that can't really be just split is the websocket interface. That currently handles all of it. Splitting that into separate parts for system dependent and independent would make it quite clunky. This would instead need a separate implementation for the library. The library would also need a separate parser for a new simplified configuration format.

> I don't feel it's a niche case --- as far as I see it, music players are the biggest customers of your dsp engine.

It might be a large niche with many deployed systems, but I still think it's a niche. We are talking about very specialized systems where MPD is the only app that will ever output sound.

> MPD needs to have a DSP pipeline to better support such transformation. However I don't think the developer is interested in that.

Not having that would be a major roadblock. If it can't be used for crossovers, then I don't think it's very interesting.

All in all making a c lib would take a quite large amount of work, and I won't have any time for it any time soon. But it depends a lot on what the MPD developer says. I'll watch the issue you opened there.

**Comment by bitkeeper** [comment]
A little bit late to the party, audio distributions like moOde use multiple sound sources (see an overview of moOde on https://www.bitlab.nl/page_id=872 including the current alsa configurations).

This would make integration in MPD it self not useable. For example for alsa based system it probally would require a new alsa plugin to replace the current alsa_cdsp plugin.

The _'hacking'_ part has mostly to do with when the audio source format is changed. The routing is just like with all other audio plugins.

@Wang-Yue 
So yes technical wise the library is nicer, but practical I have my doubts.
But if you want to prove your case; create a library or plugin (which just still starts camilladsp with IPC communication) and demonstrates how easy it is to integrate it into other existing application and sound architectures.

**Comment by HEnquist** [comment]
Considering the lack of responses to the issue at MPD, I'm closing this. Please reopen if something changes.
