### ISSUE TITLE
Add support for wav-files with WAVE_FORMAT_EXTENSIBLE header

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camilladsp#124]
Not sure if you are interesseted in it , but at the moOde forum there was a user which had camilladsp problems with the attached ir file.
Also I couldn't also read it with REW. Soxr and Audacity didn't have problems with it.
It did concern a wave file 32bit float at 96kHz, that was created with Audio Lense.

Saving with (audacity) or converting with sox to just 32 bit float as output fixed the issue. So expecting some wave header trouble ;-)

[B&K8 32Bit_Front Left_96.zip](https://github.com/HEnquist/camilladsp/files/6831444/B.K8.32Bit_Front.Left_96.zip)

**Comment by HEnquist** [comment]
This file is using the rather unusual WAVE_FORMAT_EXTENSIBLE format of the header. I have kept the wav-reader of CamillaDSP simple, so it can only read a normal header. It should give an error saying that this file has an unsupported wave format.
The validator in pycamilladsp-plot (used in the gui) should agree on that.
Adding support for this header is certainly possible, but since there is an easy workaround of rewriting the files with some other software I won't put it at the top of my priority list :)

**Comment by bitkeeper** [comment]
Thanks for the quick answer!
It isn't also on my list ;-), the work arround is easy enough.

Now we are just aware of the fact that users with Audio Lense need to convert it first.

**Comment by HEnquist** [comment]
> It isn't also on my list ;-), the work arround is easy enough.

I have put it on my list, just not at the top :)
> Now we are just aware of the fact that users with Audio Lense need to convert it first.

I'll add a line about that in the readme!

**Comment by HEnquist** [comment]
included in 0.6.2

**Comment by bitkeeper** [comment]
Confirmed fix (tested with 6.3) :-)

**Comment by HonestJohn61** [comment]
Brilliant! Just updated from 0.6.1 to 0.6.3 when I discovered that this was why my Audiolense convolution filter wouldn't work. Thanks again Henrik for keeping on working on this!
