### ISSUE TITLE
free output device when paused

### ISSUE THREAD

**Issue by DeLub** [HEnquist/camilladsp#132]
I have a udev rule configured that switches off my dac when it is not in use. This works fine for e.g., Roon. But now I’ve switched to CamillaDSP on a Pi that functions as a USB gadget…

Is it possible to free the alsa output device when no sound is output? (i.e., when CamillaDSP is paused?)

**Comment by HEnquist** [comment]
CamillaDSP can't release a device while running, so the only way to release is to stop it completely.
If you want to do that, you will need to some (python) script that keeps watching camilladsp, and stops it when it pauses. Then the challenge becomes how to determine that it's time to start again. You would need to try capturing from the gadget to see if it has become active again.
There are changes coming to the gadget driver, that will make it much easier to do things like this. But that will likely be in a kernel several versions from now.

**Comment by DeLub** [comment]
Hmm… I’m only talking about freeing the output device, why would that need changes from the gadget driver? Roon also kept running continously,claiming and freeing the output device as was necessary.

**Comment by HEnquist** [comment]
The gadget driver changes will just make a workaround much simpler to implement. It's not needed to add the release functionality in camilladsp.
I'll have to think about what it would mean to close the device while paused. But I can already say that it's a large change to the playback code, so it's not something that will happen soon.

**Comment by t123yh** [comment]
Even without USB gadget, I think a pause feature may be desired, e.g. if we use bluez-alsa or shairport-sync for audio source.

**Comment by kbasaran** [comment]
Related to this, I used the 'Stop' command to bring camilladsp to "Inactive" state, yet I see that this didn't reduce power consumption in comparison to 'Paused' state. There is in both cases an additional 7W power draw on the line. Only when I exit the application this goes away. I assume the sound card also goes to sleep with it, 7W cannot be the Raspberry Pi CPU. Is this all expected behaviour?

**Comment by HEnquist** [comment]
I would expect the sound card to go to sleep in the inactive state. Camilladsp drops the reference to it which triggers a call to close the device: https://github.com/diwic/alsa-rs/blob/a323c994bb7dba52f22e2247ff088ed5194532e2/src/pcm.rs#L297
Don't know why this isn't enough to put the card to sleep.

**Comment by kbasaran** [comment]
OK, my bad. It turns out when CamillaDSP exits, it takes down with it my daemon that controls the amplifier. This causes shut down of amplifier PSU, which accounts for the 7W.
I turned off the amplifier completely and having CamillaDSP in any state including terminated, I cannot detect a change above the ~1W noise that my measurement tool has. I was looking at the wrong place for power savings.

**Comment by HEnquist** [comment]
I have decide to not implement the functionality to release the output device when paused. It needs too large changes to parts that are already complicated enough. The workaround is to stop camilladsp until there is something to process.
