### ISSUE TITLE
Using alsa_cdsp with incoming audio being streamed to loopback or hw type pcm ALSA device

### ISSUE THREAD

**Issue by HonestJohn61** [HEnquist/camilladsp#139]
Hi, This is a fantastic project that I'm currently using every day with Roon streaming to a loopback device on an RPi4 running RoonBridge and Camilla, connected to a MOTU UltraLite-mk5 by USB. All working fine, but I'd really like to use alsa_cdsp to incorporate dynamic sample rate matching.

The issue is that alsa_cdsp relies on a cdsp PCM type device, and RoonBridge can only interact with hw type devices ([here's Roon's response to my question to them](https://community.roonlabs.com/t/roonbridge-on-linux-connection-to-linux-pcm-device-of-a-type-other-than-hw/172149)).

Are there any possibilities to overcome this issue? I have some Home Automation apps running on my home network (openHAB, node-RED and MQTT) which I mention just in case they'd be any use in setting up a workaround, but I'm not able to code myself, and my knowledge of Linux at this point is very basic.

Many thanks

**Comment by HEnquist** [comment]
Hmm the answer from Roon that it can't be modified to accept PCM devices doesn't make a lot of sense. It most certainly can, but for some reason they don't want to.
Changing the CDSP plugin to a hw device would mean it would need to become a virtual sound card driver, meaning a kernel module. Certainly possible, but far too much work!
The Loopback is supposed to have an optional mode where it can allow an application to open the playback side at a new rate (which would then notify the capture side). Unfortunately that functionality is broken since a long time. There also seems to be no ongoing work to fix it. 
The last option, which will likely solve many use cases, is to use the usb gadget mode on a separate Pi4. Then Roon would run on one Pi, connected via a usb cable to a second one that runs camilladsp. This requires the not yet finished multi-rate functionality of the usb gadget driver. It will probably a couple of more kernel releases until that's finished.

**Comment by HonestJohn61** [comment]
Thanks Henrik for your reply. I guess that's the end of the line for me trying to change Camilla's sampling rate dynamically when streaming from Roon.

One last question: is it possible to configure an ALSA loopback device to have the MOTU hw card as a slave? I guess not, but thought I'd ask.

Thanks again.

**Comment by HEnquist** [comment]
Slaving devices also requires using a PCM device, so unfortunately not an option for Roon.
IMO not supporting PCM devices is a very weird decision. I would at least try to press them for an answer to why they don't want to.

**Comment by HonestJohn61** [comment]
Thanks again Henrik

**Comment by HEnquist** [comment]
There is nothing to do about this on the camilladsp side of things, so I'm closing this issue.

**Comment by HonestJohn61** [comment]
Hi Henrik

I got this back from Jaroslav:

_

> On 29. 09. 21 18:46, John Warden wrote:
> Hi Jaroslav
> From a bit of Googling I understand that you’re the creator and owner of alsaloop, and I wanted to clarify an assertion that was made to me about a problem with alsaloop’s handling of changing playback rates.
> 
> You probably mean the snd-aloop kernel driver (which has the Loopback card identifier). We had some discussion a more than year ago:
> 
> https://lore.kernel.org/all/b4af9071-f8d7-5b47-4d7a-c5743bd67394@ivitera.com/
> 
> There is no solution for this issue at the moment.
> 
> If you mean something other, let me know.
> 
> 						Jaroslav
> 
> -- 
> Jaroslav Kysela <perex@perex.cz>
> Linux Sound Maintainer; ALSA Project; Red Hat, Inc.

Is this the issue you were referring to? Is it just stuck until someone comes up with a potential solution or is it a question of resource? I know all of this is done mostly by volunteer work, which is just amazing!

Alternatively I might just go down the route of the second RPi4 and USB gadget ... if that gets fixed!
_

**Comment by HEnquist** [comment]
Yes it's exactly that issue. I don't think there are any major roadblocks, it's just stuck until someone finds the time to work on it.

I'm guessing the sample rate switching of the USB gadget mode will be ready long before the Loopback is fixed.
