### ISSUE TITLE
Buffer added after Xruns with JACK/Pipewire-Jack

### ISSUE THREAD

**Issue by tiny69712** [HEnquist/camilladsp#232]
Hello, 
I'm using CamillaDSP for testing the limit of latency with JACK and Pipewire-Jack backend and I give the server configuration the smallest buffer size possible.
So it's normally that the Xruns will appear, but what I did not expect is that when the log show me a new Xrun error, the latency increase straightway like that something just added the buffers to prevent this. 
I just want to ask if this is maybe a feature of CamillaDSP or a backend feature in libjack.
Thanks

**Comment by HEnquist** [comment]
When CamillaDSP encounters a buffer underrun it delays the stream a little before continuing. This is done to let the buffers fill up a little, to reduce the risk of getting another underrun. I have done it like this because the primary use case is listening to recorded music, where avoiding annoying underruns is more important than very low latency.

**Comment by tiny69712** [comment]
Okay it's clear thank you.
