### ISSUE TITLE
Remember volume level on restart

### ISSUE THREAD

**Issue by KR4DIO** [HEnquist/camilladsp#265]
Would it be possible to add a way to store the volume level so that it can be restored if camilladsp is restarted?

**Comment by HEnquist** [comment]
What use case do you have in mind?
It could be done by adding another file where it stores the current state. That could then store current volume and mute state. The path to the currently loaded config file could also be stored there. I think this is a nice improvement. I'll think some more about how this is best implemented, and when to do it. I wasn't planning on any more major changes for version 2.0, but this could go in if it turns out to be easy.

**Comment by KR4DIO** [comment]
I have a media computer for music and movies, and I'm using camilladsp for the speaker crossovers and room correction. I wrote a little script to send remote control volume events to camilla, which works great. However, if I'm listening to background music level at -18dB, stop for a while, and camilladsp restarts for some reason (system updates, power outage, etc), when I come back and press play the volume is now at 0dB.

Thank you for the all the work you put into this amazing tool!

**Comment by HEnquist** [comment]
Ok! For now, you can improve things by adding an initial volume setting to the launch command. If you let it start at -20 instead, it just gets a bit silent instead of blasting away at full volume.

**Comment by KR4DIO** [comment]
How did I miss that command line option? I can just have my remote control script write to a file and reference it in the camilladsp launch command. Feel free to close the issue if this feature is out of scope for the project.

**Comment by HEnquist** [comment]
Great that you found a way around your problem!
Let's keep the issue open though. I still think it's useful to add a way to make the volume persistent.
