### ISSUE TITLE
Issue when running Build Command

### ISSUE THREAD

**Issue by Simba14** [HEnquist/camilladsp#321]
**Describe the bug**
Hey gang, thanks for building this great tool.
Sorry I'm brand new to rust and having an issue when running the build command:
`RUSTFLAGS='-C target-cpu=native' cargo build --release`
I get the following error:
```
could not find `Cargo.toml` in `/Users/me/.cargo` or any parent directory
```
Do I need to clone this repository and run it inside the directory?

**To Reproduce**
1. Install rust (https://rustup.rs/)
2. Run the command `RUSTFLAGS='-C target-cpu=native' cargo build --release`
3. See error

**System info**
- Apple M1
- cpu architecture
- camilladsp version

**Comment by HEnquist** [comment]
Yes you must download the source code before you can compile. Either clone with git or download the sources as a zip file.

**Comment by Simba14** [comment]
Thanks for the speedy reply. Sorry I'm quite new to all of this!

Is the build step necessary to run `camilladsp`?
I have installed `camilladsp-macos-aarch64.tar.gz` (v2.0.1), which gives me the executable file as expected. 

When I try to run the executable file (without the cloning this repo / building) I get the following issue (the session ends automatically and there isn't any error logged). Warning from Iterm indicates a broken pipe issue:
<img width="1312" alt="Screenshot 2024-02-09 at 14 06 50" src="https://github.com/HEnquist/camilladsp/assets/16307049/ab211d95-6116-4abd-86e8-ac70446b6c3e">


Do you know what I could be doing wrong?

**Comment by HEnquist** [comment]
No you don't need to build it yourself unless you want to customize it somehow. The pre-built binaries are usually fine, just use that.

That result above is the expected outcome. You need to provide a config file or start the websocket server and enable wait mode, otherwise it will just print this help text and exit. 
Please go through the readme, it describes the config file and how to make it. If you don't want to write it by hand, then set up the GUI. You'll find it here: https://github.com/HEnquist/camillagui-backend
There is also a long thread at diy audio, which I think is the best place to ask for assistance. 
https://www.diyaudio.com/community/threads/camilladsp-cross-platform-iir-and-fir-engine-for-crossovers-room-correction-etc.349818/

**Comment by HEnquist** [comment]
Here is a guide specifically for Mac: https://www.diyaudio.com/community/threads/camilladsp-cross-platform-iir-and-fir-engine-for-crossovers-room-correction-etc.349818/page-177#post-7131218

**Comment by Simba14** [comment]
Thanks, really appreciate you pointing me in the right direction!
