### ISSUE TITLE
Pipeline: Various sample rates in -> Resampling -> Filters -> Target sample rate out

### ISSUE THREAD

**Issue by jonach66** [HEnquist/camilladsp#41]
Dear Henrik,
I`m using different sources (different sample rates too), so resampling is a necessity to apply filters (FIR) without changing the filter files frequently.

Is the following audio pipeline possible? How to setup?

various (changing from song to song) sampling rates in from ALSA capture loop -> “automatic” resampling to target (fixed) sampling rate -> filters (FIR and others) -> Target (fixed) sample rate out to ALSA Playback loop?

In such a setup just one filter setup could be used, no filter switching needed. Setup should then avoid resampling in ALSA (I have to find out how, but should be possible).

Kind regards!
Josef, a 24/7 user of CamillaDSP

**Comment by HEnquist** [comment]
Hi Josef!
This is something I would like to implement. Unfortunately thers is currently no easy way to know when the source wanted to change sample rate. The alsa loopback device is supposed to be able to break the capture when the source changes format or rate, but this is currently broken. See here:
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-March/165454.html
So currently, if the player tries to change the sample rate, it will just fail. Once this bug is fixed, it will instead break the capture of camilladsp, and then it would be easy to just get the new value, update the resampling settings, and reconnect.

**Comment by jonach66** [comment]
Thank you for the prompt answer! So I have to wait patiently!
Kind regards!
Josef

**Comment by t123yh** [comment]
Hi, as a year has passed, may I ask if there is any new progress on this? Being able to handle arbitrary sample rate is crucial in some circumstances.

Thanks!

**Comment by HEnquist** [comment]
The Alsa loopback still has this issue, although I think a fix is on it's way. 
But there is an alternative solution! Please see the CDSP Alsa plugin by Scripple: https://github.com/scripple/alsa_cdsp
Using that, sample rate switching works just fine.

**Comment by t123yh** [comment]
> The Alsa loopback still has this issue, although I think a fix is on it's way.

Would you please share a link to the fix so we can track its progress? Thanks!

> But there is an alternative solution! Please see the CDSP Alsa plugin by Scripple: https://github.com/scripple/alsa_cdsp
> Using that, sample rate switching works just fine.

This solution have some limitations (for example, parameters adjusted with WebSocket are lost), which are not desired. So how's the idea that we implement an ALSA I/O plugin directly within CamillaDSP as another type of CaptureDevice/PlaybackDevice? I want try to implement this, but I would like to know if the direction goes correct.

**Comment by HEnquist** [comment]
This is the fix I was thinking about: https://mailman.alsa-project.org/pipermail/alsa-devel/2021-April/183254.html
I have not tried it yet.

Putting the Alsa i/o plugin inside camilladsp would not be very different from the separate plugin. Such a plugin is stopped and reloaded on sample rate changes. Putting it inside means all of camillladsp will be closed and reloaded, and then the current config is lost. 
I think a separate plugin is really the way to go. One improvement could be to use a named pipe instead of stdin/out, let camillladsp run all the time, and let the plugin control it via the websocket.

**Comment by HEnquist** [comment]
It looks like the loopback fix will be included in kernel 5.13 that will likely be released in a few weeks.

**Comment by t123yh** [comment]
> It looks like the loopback fix will be included in kernel 5.13 that will likely be released in a few weeks.

It seems that it's already been included the 5.10.x stable branch since .40 or an earlier version. Could you possibly implement the dynamic resampling feature now?

**Comment by HEnquist** [comment]
Yes you are right, it's already in the 5.12.8 I'm running now. Just tried it with aplay and arecord, but sadly it still doesn't work.

Once this starts working (who knows when) it will just break capture when the rate changes. There is no notification of what happened. You will still need to tell camilladsp what to do next using some script.

**Comment by t123yh** [comment]
Ok then, maybe it's best to implement the previous idea that we create a alsa I/O device ourself, rather than relying on the loop. I'll try to do it.

**Comment by HEnquist** [comment]
Sure, just go ahead! I would use the existing plugin as a starting point, a lot of effort went into getting it working properly.

**Comment by HEnquist** [comment]
I don't think there has been any progress unfortunately.
