### ISSUE TITLE
Problem with acourate wav files

### ISSUE THREAD

**Issue by EricXh** [HEnquist/camilladsp#94]
I want to use moodeaudio 7.1 beta, had a lot of discussion with user bitlab, but we do not find any mistake why it is not working.
I have coefficient files form Audiovero called acourate.
`Audio
Format                                   : PCM
Format profile                           : Float
Codec ID                                 : 3
Codec ID/Hint                            : IEEE 
Duration                                 : 682 ms
Bit rate mode                            : Constant
Bit rate                                 : 49.2 Mb/s
Channel(s)                               : 2 channels
Sampling rate                            : 384 kHz
Bit depth                                : 64 bits
Stream size                              : 4.00 MiB (100%)`

My DAC is switching constantly between 44,1 and the sampling frequency of the file with no sound.
The yaml file should be correct, a flat file is running correctly.
I also tried to save the wav file in Audacity as 32 float and 24 int file, but no success.
Hope you have an idea.

BR
Erich
[Cor1S384000.zip](https://github.com/HEnquist/camilladsp/files/6017951/Cor1S384000.zip)

**Comment by HEnquist** [comment]
Hi,
It would be very useful to have the log output of camilladsp. There should be some message telling why it exits.

Just looking at the coeff file, I notice that it's very long (262k taps) and at very high sample rate (384 kHz). Since you mention moode, I assume you are running on a raspberry pi. It could simply be that the pi isn't able to keep up. 
It's also a stereo file, something CamillaDSP can't handle. It will instead read it as one channel with twice as many samples.
A few things to try:
- if you can increase the chunksize, try that first. Go to at least 8192 (and keep it a power of two).
- make the coefficients shorter. Of the 262k taps, there are about 70k at the start and 40k at the end that are below -100dB. This isn't really contributing to anything, but still eats processing power.
- make sure you have only one channel in each coefficient file

**Comment by EricXh** [comment]
Hi,
I use now dbl instead of wav files (found this info in an german forum).
In L and R  ;-)
Now with increased chuncksize of 16384 or 32768 it is running!

BR
Erich

**Comment by HEnquist** [comment]
Great! What cpu load do you get when running then?
I will add some more text on the readme on coeff file formats, will hopefully help avoiding some confusion.

**Comment by EricXh** [comment]
I played more, but with chuncksize of 16384 it is to less, so 32768 is the way.
Problem is the start of a song, its stuttering a lot.
Problem is the resampling to 384kHz, I struggle to get it running with camilladsp.
When I use soxr before, the convolving is done on the heavy samplerate, so it would be nice to resample after convolving.
But thats a different story.

**Comment by HEnquist** [comment]
384 kHz is pretty high. The problem is that things aren't linear. When you double the sample rate, the actual load on the DSP goes up by roughly a factor 4. 
I spent quite some time thinking if the resampler should be at the input or output side. There are pros and cons with both, but in total there are more reasons to put it at the input side than the output.
